<a href="https://colab.research.google.com/github/0xmitsui/python_basics/blob/main/Copy_of_Pandas_beginners_2025_cohort3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the pandas library
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Datafrane: This is a pandas method for creating table

data= {"Name": ["David", "Queen", "Peace", "Williams", "Washington", "Teslim", "Sharon", "Faith", "Charles", "Laura"],


      "State": ["Kwara", "Akwa Ibom", "Enugu", "Kogi", "Ogun", "Oyo", "Abuja", "Nasarawa", "Abuja", "Abi"],

       "Course": ["Computer Science", "Computer Engineering", "Computer Engineering", "Software Engineer", "Computer Engineering", "Computer Science", "Data Science", "AI", "Machine Learning", "Mathematics"],


       "School": ["Nile University", "Afebabalola University", "University of Nigeria", "Veritas", "Hill-Side University", "Nile", "University of Abuja", "University of Abuja", "University of Abuja", "University of Abuja"]


}

In [ ]:
df = pd.DataFrame(data)
df

         Name      State                Course                  School
0       David      Kwara      Computer Science         Nile University
1       Queen  Akwa Ibom  Computer Engineering  Afebabalola University
2       Peace      Enugu  Computer Engineering   University of Nigeria
3    Williams       Kogi     Software Engineer                 Veritas
4  Washington       Ogun  Computer Engineering    Hill-Side University
5      Teslim        Oyo      Computer Science                    Nile
6      Sharon      Abuja          Data Science     University of Abuja
7       Faith   Nasarawa                    AI     University of Abuja
8     Charles      Abuja      Machine Learning     University of Abuja
9       Laura        Abi           Mathematics     University of Abuja

**GETTING DATA FROM EXTERNAL SOURCES**

In [ ]:
# loading or reading the dataset from my local machine
election_df = pd.read_csv("/content/HoC-GE2024-results-by-candidate.csv")

In [ ]:
# after loading the dataset, we have to view it
election_df

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Heritage Party,HPUK,PP12550,...,Rhiannon,Morrissey,Female,No,No,NaN,183,0.005118,NaN,117009
1,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Independent,Ind,NaN,...,Captain,Beany,Male,No,No,NaN,618,0.017284,NaN,20
2,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Liberal Democrat,LD,PP90,...,Justin,Griffiths,Male,No,No,NaN,916,0.025619,-0.011412,89373
3,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Green,Green,PP63,...,Nigel,Hill,Male,No,No,NaN,1094,0.030597,0.014817,92890
4,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Conservative,Con,PP52,...,Abigail,Mainon,Female,No,No,NaN,2903,0.081191,-0.145088,72976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4510,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Green,Green,PP63,...,Michael,Kearney,Male,No,No,NaN,2212,0.043283,0.043118,101413
4511,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Liberal Democrat,LD,PP90,...,Andrew,Hollyer,Male,No,No,NaN,5496,0.107541,-0.079162,34649
4512,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Reform UK,RUK,PP7931,...,John,Crispin-Bailey,Male,No,No,NaN,5912,0.115681,0.110877,117283
4513,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Conservative,Con,PP52,...,Julian,Sturdy,Male,Yes,Yes,4079.0,13770,0.269440,-0.226871,4113
4514,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Labour,Lab,PP53,...,Luke,Charters,Male,No,No,5199.0,23161,0.453195,0.153816,3440

In [ ]:
# using for loop to retrieve the names of all the variables in the dataset
for col in election_df.columns:
  print(col)

ONS ID
ONS region ID
Constituency name
County name
Region name
Country name
Constituency type
Party name
Party abbreviation
Electoral Commission party ID
MNIS party ID
Electoral Commission adjunct party ID
Candidate first name
Candidate surname
Candidate gender
Sitting MP
Former MP
Member MNIS ID
Votes
Share
Change
DC Person ID

In [ ]:
# using another method from pandas to view the variables name
election_df.columns

Index(['ONS ID', 'ONS region ID', 'Constituency name', 'County name',
       'Region name', 'Country name', 'Constituency type', 'Party name',
       'Party abbreviation', 'Electoral Commission party ID', 'MNIS party ID',
       'Electoral Commission adjunct party ID', 'Candidate first name',
       'Candidate surname', 'Candidate gender', 'Sitting MP', 'Former MP',
       'Member MNIS ID', 'Votes', 'Share', 'Change', 'DC Person ID'],
      dtype='object')

In [ ]:
election_df.head()

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Heritage Party,HPUK,PP12550,...,Rhiannon,Morrissey,Female,No,No,NaN,183,0.005118,NaN,117009
1,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Independent,Ind,NaN,...,Captain,Beany,Male,No,No,NaN,618,0.017284,NaN,20
2,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Liberal Democrat,LD,PP90,...,Justin,Griffiths,Male,No,No,NaN,916,0.025619,-0.011412,89373
3,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Green,Green,PP63,...,Nigel,Hill,Male,No,No,NaN,1094,0.030597,0.014817,92890
4,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Conservative,Con,PP52,...,Abigail,Mainon,Female,No,No,NaN,2903,0.081191,-0.145088,72976

In [ ]:
election_df.head(30)

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Heritage Party,HPUK,PP12550,...,Rhiannon,Morrissey,Female,No,No,NaN,183,0.005118,NaN,117009
1,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Independent,Ind,NaN,...,Captain,Beany,Male,No,No,NaN,618,0.017284,NaN,20
2,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Liberal Democrat,LD,PP90,...,Justin,Griffiths,Male,No,No,NaN,916,0.025619,-0.011412,89373
3,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Green,Green,PP63,...,Nigel,Hill,Male,No,No,NaN,1094,0.030597,0.014817,92890
4,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Conservative,Con,PP52,...,Abigail,Mainon,Female,No,No,NaN,2903,0.081191,-0.145088,72976
5,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Plaid Cymru,PC,PP77,...,Colin,Deere,Male,No,No,NaN,4719,0.131982,0.042141,94730
6,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Reform UK,RUK,PP7931,...,Mark,Griffiths,Male,No,No,NaN,7484,0.209313,0.123907,117844
7,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Labour,Lab,PP53,...,Stephen,Kinnock,Male,Yes,Yes,4359.0,17838,0.498895,-0.030313,4252
8,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Trade Unionist and Socialist Coalition,TUSC,PP804,...,Lucas,Grant,Male,No,No,NaN,214,0.005084,NaN,74393
9,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Scottish Family Party,SFP,PP6380,...,Dawn,Smith,Female,No,No,NaN,352,0.008362,NaN,85468
10,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Alba Party,Alba,PP12700,...,Charlie,Abel,Male,No,No,NaN,703,0.016700,NaN,85442
11,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Scottish Green Party,Green,PP130,...,Esme,Houston,Female,No,No,NaN,1275,0.030289,0.018080,85482
12,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Liberal Democrat,LD,PP90,...,Desmond,Bouse,Male,No,No,NaN,2583,0.061361,-0.015942,74392
13,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Reform UK,RUK,PP7931,...,Kenneth,Leggat,Male,No,No,NaN,3781,0.089821,0.073602,117290
14,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Conservative,Con,PP52,...,Gillian,Tebberen,Female,No,No,NaN,5881,0.139708,-0.105789,74616
15,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Labour,Lab,PP53,...,Lynn,Thomson,Female,No,No,NaN,12773,0.303433,0.183637,21097
16,S14000060,S92000003,Aberdeen North,NaN,Scotland,Scotland,Burgh,Scottish National Party,SNP,PP102,...,Kirsty,Blackman,Female,Yes,Yes,4357.0,14533,0.345243,-0.183733,6042
17,S14000061,S92000003,Aberdeen South,NaN,Scotland,Scotland,Burgh,Independent,Ind,NaN,...,Sophie,Molly,Female,No,No,NaN,225,0.004855,NaN,114595
18,S14000061,S92000003,Aberdeen South,NaN,Scotland,Scotland,Burgh,Scottish Family Party,SFP,PP6380,...,Graeme,Craib,Male,No,No,NaN,423,0.009127,NaN,85486
19,S14000061,S92000003,Aberdeen South,NaN,Scotland,Scotland,Burgh,Scottish Green Party,Green,PP130,...,Guy,Ingerson,Male,No,No,NaN,1609,0.034718,0.029371,20500
20,S14000061,S92000003,Aberdeen South,NaN,Scotland,Scotland,Burgh,Liberal Democrat,LD,PP90,...,Jeff,Goodhall,Male,No,No,NaN,2921,0.063027,-0.043880,21470
21,S14000061,S92000003,Aberdeen South,NaN,Scotland,Scotland,Burgh,Reform UK,RUK,PP7931,...,Michael,Pearce,Male,No,No,NaN,3199,0.069026,0.065135,117386
22,S14000061,S92000003,Aberdeen South,NaN,Scotland,Scotland,Burgh,Conservative,Con,PP52,...,John,Wheeler,Male,No,No,NaN,11300,0.243823,-0.099766,21078
23,S14000061,S92000003,Aberdeen South,NaN,Scotland,Scotland,Burgh,Labour,Lab,PP53,...,Mohammad,Malik,Male,No,No,NaN,11455,0.247168,0.159495,19868
24,S14000061,S92000003,Aberdeen South,NaN,Scotland,Scotland,Burgh,Scottish National Party,SNP,PP102,...,Stephen,Flynn,Male,Yes,Yes,4735.0,15213,0.328255,-0.124336,21095
25,S14000062,S92000003,Aberdeenshire North and Moray East,NaN,Scotland,Scotland,County,Liberal Democrat,LD,PP90,...,Ian,Bailey,Male,No,No,NaN,2782,0.072850,0.028658,85524
26,S14000062,S92000003,Aberdeenshire North and Moray East,NaN,Scotland,Scotland,County,Labour,Lab,PP53,...,Andy,Brown,Male,No,No,NaN,3876,0.101498,0.059790,74459
27,S14000062,S92000003,Aberdeenshire North and Moray East,NaN,Scotland,Scotland,County,Reform UK,RUK,PP7931,...,Jo,Hart,Female,No,No,NaN,5562,0.145648,NaN,117298
28,S14000062,S92000003,Aberdeenshire North and Moray East,NaN,Scotland,Scotland,County,Conservative,Con,PP52,...,Douglas,Ross,Male,Yes,Yes,4627.0,12513,0.327668,-0.155520,2756
29,S14000062,S92000003,Aberdeenshire North and Moray East,NaN,Scotland,Scotland,County,Scottish National Party,SNP,PP102,...,Seamus,Logan,Male,No,No,5280.0,13455,0.352336,-0.078577,85513

In [ ]:
election_df.tail()

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
4510,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Green,Green,PP63,...,Michael,Kearney,Male,No,No,NaN,2212,0.043283,0.043118,101413
4511,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Liberal Democrat,LD,PP90,...,Andrew,Hollyer,Male,No,No,NaN,5496,0.107541,-0.079162,34649
4512,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Reform UK,RUK,PP7931,...,John,Crispin-Bailey,Male,No,No,NaN,5912,0.115681,0.110877,117283
4513,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Conservative,Con,PP52,...,Julian,Sturdy,Male,Yes,Yes,4079.0,13770,0.269440,-0.226871,4113
4514,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Labour,Lab,PP53,...,Luke,Charters,Male,No,No,5199.0,23161,0.453195,0.153816,3440

In [ ]:
election_df.tail(10)

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
4505,E14001604,E12000003,York Central,NaN,Yorkshire and The Humber,England,Borough,Labour and Co-operative,Lab,PP53,...,Rachael,Maskell,Female,Yes,Yes,4471.0,24537,0.566374,0.002324,6364
4506,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Independent,Ind,NaN,...,Darren,Borrows,Male,No,No,NaN,66,0.001291,NaN,117282
4507,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Independent,Ind,NaN,...,Hal,Mayne,Male,No,No,NaN,88,0.001722,NaN,117285
4508,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Independent,Ind,NaN,...,Keith,Hayden,Male,No,No,NaN,141,0.002759,NaN,117284
4509,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,The Yorkshire Party,Yrks,PP2055,...,David,Eadington,Male,No,No,NaN,260,0.005087,NaN,117115
4510,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Green,Green,PP63,...,Michael,Kearney,Male,No,No,NaN,2212,0.043283,0.043118,101413
4511,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Liberal Democrat,LD,PP90,...,Andrew,Hollyer,Male,No,No,NaN,5496,0.107541,-0.079162,34649
4512,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Reform UK,RUK,PP7931,...,John,Crispin-Bailey,Male,No,No,NaN,5912,0.115681,0.110877,117283
4513,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Conservative,Con,PP52,...,Julian,Sturdy,Male,Yes,Yes,4079.0,13770,0.269440,-0.226871,4113
4514,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Labour,Lab,PP53,...,Luke,Charters,Male,No,No,5199.0,23161,0.453195,0.153816,3440

In [ ]:
df_sample= election_df.head(100)
df_sample

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Heritage Party,HPUK,PP12550,...,Rhiannon,Morrissey,Female,No,No,NaN,183,0.005118,NaN,117009
1,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Independent,Ind,NaN,...,Captain,Beany,Male,No,No,NaN,618,0.017284,NaN,20
2,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Liberal Democrat,LD,PP90,...,Justin,Griffiths,Male,No,No,NaN,916,0.025619,-0.011412,89373
3,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Green,Green,PP63,...,Nigel,Hill,Male,No,No,NaN,1094,0.030597,0.014817,92890
4,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Conservative,Con,PP52,...,Abigail,Mainon,Female,No,No,NaN,2903,0.081191,-0.145088,72976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,E14001067,E12000008,Arundel and South Downs,NaN,South East,England,County,Green,Green,PP63,...,Steve,McAuliffe,Male,No,No,NaN,5515,0.100749,0.060959,95444
96,E14001067,E12000008,Arundel and South Downs,NaN,South East,England,County,Reform UK,RUK,PP7931,...,David,Thomas,Male,No,No,NaN,7391,0.135020,NaN,116265
97,E14001067,E12000008,Arundel and South Downs,NaN,South East,England,County,Labour,Lab,PP53,...,Christopher,Philipsborn,Male,No,No,NaN,9782,0.178699,0.021949,116267
98,E14001067,E12000008,Arundel and South Downs,NaN,South East,England,County,Liberal Democrat,LD,PP90,...,Richard,Allen,Male,No,No,NaN,9867,0.180252,-0.009267,101124
99,E14001067,E12000008,Arundel and South Downs,NaN,South East,England,County,Conservative,Con,PP52,...,Andrew,Griffith,Male,Yes,Yes,4874.0,22001,0.401918,-0.202453,72040

In [ ]:
df_sample.head(71).tail(21)

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
50,S14000064,S92000003,Alloa and Grangemouth,NaN,Scotland,Scotland,County,Independent,Ind,NaN,...,Eva,Comrie,Female,No,No,NaN,881,0.021383,NaN,73804
51,S14000064,S92000003,Alloa and Grangemouth,NaN,Scotland,Scotland,County,Liberal Democrat,LD,PP90,...,Adrian,May,Male,No,No,NaN,1151,0.027936,-0.025198,72985
52,S14000064,S92000003,Alloa and Grangemouth,NaN,Scotland,Scotland,County,Scottish Green Party,Green,PP130,...,Nariese,Whyte,Female,No,No,NaN,1421,0.034489,0.019639,117137
53,S14000064,S92000003,Alloa and Grangemouth,NaN,Scotland,Scotland,County,Conservative,Con,PP52,...,Rachel,Nunn,Female,No,No,NaN,3127,0.075896,-0.172100,85377
54,S14000064,S92000003,Alloa and Grangemouth,NaN,Scotland,Scotland,County,Reform UK,RUK,PP7931,...,Richard,Fairley,Male,No,No,NaN,3804,0.092328,0.088451,114569
55,S14000064,S92000003,Alloa and Grangemouth,NaN,Scotland,Scotland,County,Scottish National Party,SNP,PP102,...,John,Nicolson,Male,Yes,Yes,4415.0,11917,0.289241,-0.237502,5926
56,S14000064,S92000003,Alloa and Grangemouth,NaN,Scotland,Scotland,County,Labour,Lab,PP53,...,Brian,Leishman,Male,No,No,5196.0,18039,0.437829,0.292794,85203
57,E14001065,E12000002,Altrincham and Sale West,NaN,North West,England,Borough,Workers Party of Britain,WPB,PP11382,...,Faisal,Kabir,Male,No,No,NaN,643,0.012497,NaN,116931
58,E14001065,E12000002,Altrincham and Sale West,NaN,North West,England,Borough,Green,Green,PP63,...,Geraldine,Coggins,Female,No,No,NaN,3699,0.071892,0.043296,4639
59,E14001065,E12000002,Altrincham and Sale West,NaN,North West,England,Borough,Liberal Democrat,LD,PP90,...,Jane,Brophy,Female,No,No,NaN,4727,0.091872,-0.018348,1432
60,E14001065,E12000002,Altrincham and Sale West,NaN,North West,England,Borough,Reform UK,RUK,PP7931,...,Paul,Swansborough,Male,No,No,NaN,4961,0.096420,NaN,4058
61,E14001065,E12000002,Altrincham and Sale West,NaN,North West,England,Borough,Conservative,Con,PP52,...,Oliver,Carroll,Male,No,No,NaN,16624,0.323097,-0.157355,116122
62,E14001065,E12000002,Altrincham and Sale West,NaN,North West,England,Borough,Labour,Lab,PP53,...,Connor,Rand,Male,No,No,5159.0,20798,0.404221,0.035871,116848
63,W07000082,W92000004,Alyn and Deeside,NaN,Wales,Wales,County,Independent,Ind,NaN,...,Edwin,Duggan,Male,No,No,NaN,1575,0.036297,NaN,116864
64,W07000082,W92000004,Alyn and Deeside,NaN,Wales,Wales,County,Green,Green,PP63,...,Karl,Macnaughton,Male,No,No,NaN,1926,0.044386,NaN,1431
65,W07000082,W92000004,Alyn and Deeside,NaN,Wales,Wales,County,Plaid Cymru,PC,PP77,...,Jack,Morris,Male,No,No,NaN,1938,0.044663,0.010642,74108
66,W07000082,W92000004,Alyn and Deeside,NaN,Wales,Wales,County,Liberal Democrat,LD,PP90,...,Richard,Marbrow,Male,No,No,NaN,2065,0.047589,-0.011532,2160
67,W07000082,W92000004,Alyn and Deeside,NaN,Wales,Wales,County,Conservative,Con,PP52,...,Jeremy,Kent,Male,No,No,NaN,7892,0.181877,-0.237665,72754
68,W07000082,W92000004,Alyn and Deeside,NaN,Wales,Wales,County,Reform UK,RUK,PP7931,...,Vicki,Roskams,Female,No,No,NaN,9601,0.221262,0.161338,115337
69,W07000082,W92000004,Alyn and Deeside,NaN,Wales,Wales,County,Labour,Lab,PP53,...,Mark,Tami,Male,Yes,Yes,1383.0,18395,0.423926,-0.003466,688
70,E14001066,E12000004,Amber Valley,NaN,East Midlands,England,County,Liberal Democrat,LD,PP90,...,Kate,Smith,Female,No,No,NaN,1590,0.037384,-0.025651,4920

In [ ]:
# rename method: This is a pandas method for renaming pandas variables

election_df.rename(columns={"Candidate Name": "Candidate_Name"})

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Heritage Party,HPUK,PP12550,...,Rhiannon,Morrissey,Female,No,No,NaN,183,0.005118,NaN,117009
1,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Independent,Ind,NaN,...,Captain,Beany,Male,No,No,NaN,618,0.017284,NaN,20
2,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Liberal Democrat,LD,PP90,...,Justin,Griffiths,Male,No,No,NaN,916,0.025619,-0.011412,89373
3,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Green,Green,PP63,...,Nigel,Hill,Male,No,No,NaN,1094,0.030597,0.014817,92890
4,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Conservative,Con,PP52,...,Abigail,Mainon,Female,No,No,NaN,2903,0.081191,-0.145088,72976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4510,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Green,Green,PP63,...,Michael,Kearney,Male,No,No,NaN,2212,0.043283,0.043118,101413
4511,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Liberal Democrat,LD,PP90,...,Andrew,Hollyer,Male,No,No,NaN,5496,0.107541,-0.079162,34649
4512,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Reform UK,RUK,PP7931,...,John,Crispin-Bailey,Male,No,No,NaN,5912,0.115681,0.110877,117283
4513,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Conservative,Con,PP52,...,Julian,Sturdy,Male,Yes,Yes,4079.0,13770,0.269440,-0.226871,4113
4514,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Labour,Lab,PP53,...,Luke,Charters,Male,No,No,5199.0,23161,0.453195,0.153816,3440

Assignment

1. Learning everything about pandas rename method

2. Learn loc[] and iloc[] pandas methods

3. Learn pandas replace method

4. Learn pandas fillna()

5. Learn pandas conditional filtering techniques

**MODULE 2: TASKS TO BE DONE**

**A. Handling Missing Data**

1. df.isnull() – Detect missing values.

2. df.notnull() – Detect non-missing values.

3. df.dropna() – Remove missing values.

4. df.fillna(value) – Replace missing values with a given value.


**B. Data Selection & Filtering**


1. df.loc[] – Select rows/columns by labels.

2. df.iloc[] – Select rows/columns by integer positions.

3. df.query() – Filter rows using query strings.


**C. Data Transformation**

df.rename(columns={}) – Rename columns.

df.astype() – Change column data types.

df.map() – Apply function to Series elements.

df.replace() – Replace values with others.


**D. Aggregation & Grouping**

1. df.groupby() – Group data and apply aggregation.

2. df.value_counts()

3. df.unique (): This returns the number of uni

4. df,nunique ()


F. Core Conditional Filtering

1. Boolean Indexing – df[df['col'] > 10] → Select rows where column > 10.

2. Multiple Conditions – df[(df['col1'] > 10) & (df['col2'] < 50)] → Combine with &, |, ~.

3. df.query() – df.query("col1 > 10 and col2 < 50")
  
  
  
  Value-based Filtering


4. df['col'].isin([x,y,z]) – Select rows where values are in a list.

5. df['col'].between(a, b) – Select rows where values fall between a and b.

6. df['col'].duplicated() – Filter duplicated rows.

7. df.nunique() with conditions – Identify unique counts for filtering.

      Null & Missing Data Filters

8. df[df['col'].isnull()] – Rows with missing values.

9. df[df['col'].notnull()] – Rows without missing values.

In [ ]:
election_df

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Heritage Party,HPUK,PP12550,...,Rhiannon,Morrissey,Female,No,No,NaN,183,0.005118,NaN,117009
1,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Independent,Ind,NaN,...,Captain,Beany,Male,No,No,NaN,618,0.017284,NaN,20
2,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Liberal Democrat,LD,PP90,...,Justin,Griffiths,Male,No,No,NaN,916,0.025619,-0.011412,89373
3,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Green,Green,PP63,...,Nigel,Hill,Male,No,No,NaN,1094,0.030597,0.014817,92890
4,W07000081,W92000004,Aberafan Maesteg,NaN,Wales,Wales,County,Conservative,Con,PP52,...,Abigail,Mainon,Female,No,No,NaN,2903,0.081191,-0.145088,72976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4510,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Green,Green,PP63,...,Michael,Kearney,Male,No,No,NaN,2212,0.043283,0.043118,101413
4511,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Liberal Democrat,LD,PP90,...,Andrew,Hollyer,Male,No,No,NaN,5496,0.107541,-0.079162,34649
4512,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Reform UK,RUK,PP7931,...,John,Crispin-Bailey,Male,No,No,NaN,5912,0.115681,0.110877,117283
4513,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Conservative,Con,PP52,...,Julian,Sturdy,Male,Yes,Yes,4079.0,13770,0.269440,-0.226871,4113
4514,E14001605,E12000003,York Outer,NaN,Yorkshire and The Humber,England,County,Labour,Lab,PP53,...,Luke,Charters,Male,No,No,5199.0,23161,0.453195,0.153816,3440

In [ ]:
# checking for missing values (entries) in the dataset

election_df.isnull()

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
1,False,False,False,True,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False
2,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4510,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4511,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4512,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4513,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4514,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# an alternative way of checking for missing entries in a dataset
election_df.isna()

,ONS ID,ONS region ID,Constituency name,County name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
1,False,False,False,True,False,False,False,False,False,True,...,False,False,False,False,False,True,False,False,True,False
2,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4510,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4511,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4512,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4513,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4514,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
#  checking the sum of missin entries by variables
election_df.isna().sum()

ONS ID                                      0
ONS region ID                               8
Constituency name                           0
County name                              4515
Region name                                 0
Country name                                0
Constituency type                           0
Party name                                  0
Party abbreviation                          0
Electoral Commission party ID             460
MNIS party ID                               0
Electoral Commission adjunct party ID    4466
Candidate first name                        0
Candidate surname                           0
Candidate gender                            0
Sitting MP                                  0
Former MP                                   0
Member MNIS ID                           3630
Votes                                       0
Share                                       0
Change                                   1506
DC Person ID                                0
dtype: int64

In [ ]:
# checking the sum of missin values in the entire dataset
election_df.isna().sum().sum()

np.int64(14585)

In [ ]:
# filter all the instances (rows) in the dataset with any missin value

election_df.notnull().sum().sum()

np.int64(84745)

In [ ]:
#

#without_missing_valuse= election_df.dropna()

In [ ]:
election_df.drop('County name', axis=1, inplace=True)

In [ ]:
election_df.isnull().sum().sum()

np.int64(10070)

In [ ]:
election_df.isnull().sum()

ONS ID                                      0
ONS region ID                               8
Constituency name                           0
Region name                                 0
Country name                                0
Constituency type                           0
Party name                                  0
Party abbreviation                          0
Electoral Commission party ID             460
MNIS party ID                               0
Electoral Commission adjunct party ID    4466
Candidate first name                        0
Candidate surname                           0
Candidate gender                            0
Sitting MP                                  0
Former MP                                   0
Member MNIS ID                           3630
Votes                                       0
Share                                       0
Change                                   1506
DC Person ID                                0
dtype: int64

In [ ]:
# inspecting the  Electoral Commission adjunct party ID to know the distinct values in the variable
election_df['Electoral Commission adjunct party ID'].value_counts()

Electoral Commission adjunct party ID
PP119    49
Name: count, dtype: int64

In [ ]:
election_df['Electoral Commission adjunct party ID'].fillna(value=0, inplace=True)

In [ ]:
election_df['Electoral Commission adjunct party ID'].value_counts()

Electoral Commission adjunct party ID
0        4466
PP119      49
Name: count, dtype: int64

In [ ]:
election_df[['ONS ID', 'Electoral Commission adjunct party ID']]

         ONS ID Electoral Commission adjunct party ID
0     W07000081                                     0
1     W07000081                                     0
2     W07000081                                     0
3     W07000081                                     0
4     W07000081                                     0
...         ...                                   ...
4510  E14001605                                     0
4511  E14001605                                     0
4512  E14001605                                     0
4513  E14001605                                     0
4514  E14001605                                     0

[4515 rows x 2 columns]

In [ ]:
election_df.isnull().sum()

ONS ID                                      0
ONS region ID                               8
Constituency name                           0
Region name                                 0
Country name                                0
Constituency type                           0
Party name                                  0
Party abbreviation                          0
Electoral Commission party ID             460
MNIS party ID                               0
Electoral Commission adjunct party ID       0
Candidate first name                        0
Candidate surname                           0
Candidate gender                            0
Sitting MP                                  0
Former MP                                   0
Member MNIS ID                           3630
Votes                                       0
Share                                       0
Change                                   1506
DC Person ID                                0
dtype: int64

In [ ]:
election_df[['Electoral Commission party ID', 'Member MNIS ID', 'Change']].fillna(value=0, inplace=True)

In [ ]:
election_df.isnull().sum()

ONS ID                                      0
ONS region ID                               8
Constituency name                           0
Region name                                 0
Country name                                0
Constituency type                           0
Party name                                  0
Party abbreviation                          0
Electoral Commission party ID             460
MNIS party ID                               0
Electoral Commission adjunct party ID       0
Candidate first name                        0
Candidate surname                           0
Candidate gender                            0
Sitting MP                                  0
Former MP                                   0
Member MNIS ID                           3630
Votes                                       0
Share                                       0
Change                                   1506
DC Person ID                                0
dtype: int64

In [ ]:
# filling up three variables where there were missing values using a fix value (0)
election_df['Electoral Commission party ID'].fillna(value=0, inplace=True)
election_df['Member MNIS ID'].fillna(value=0, inplace=True)
election_df['Change'].fillna(value=0, inplace=True)

In [ ]:
election_df.isnull().sum()

ONS ID                                   0
ONS region ID                            8
Constituency name                        0
Region name                              0
Country name                             0
Constituency type                        0
Party name                               0
Party abbreviation                       0
Electoral Commission party ID            0
MNIS party ID                            0
Electoral Commission adjunct party ID    0
Candidate first name                     0
Candidate surname                        0
Candidate gender                         0
Sitting MP                               0
Former MP                                0
Member MNIS ID                           0
Votes                                    0
Share                                    0
Change                                   0
DC Person ID                             0
dtype: int64

In [ ]:
# viewing the dataset
election_df

,ONS ID,ONS region ID,Constituency name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,MNIS party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Heritage Party,HPUK,PP12550,1037,...,Rhiannon,Morrissey,Female,No,No,0.0,183,0.005118,0.000000,117009
1,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Independent,Ind,0,8,...,Captain,Beany,Male,No,No,0.0,618,0.017284,0.000000,20
2,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Liberal Democrat,LD,PP90,17,...,Justin,Griffiths,Male,No,No,0.0,916,0.025619,-0.011412,89373
3,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Green,Green,PP63,44,...,Nigel,Hill,Male,No,No,0.0,1094,0.030597,0.014817,92890
4,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Conservative,Con,PP52,4,...,Abigail,Mainon,Female,No,No,0.0,2903,0.081191,-0.145088,72976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4510,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Green,Green,PP63,44,...,Michael,Kearney,Male,No,No,0.0,2212,0.043283,0.043118,101413
4511,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Liberal Democrat,LD,PP90,17,...,Andrew,Hollyer,Male,No,No,0.0,5496,0.107541,-0.079162,34649
4512,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Reform UK,RUK,PP7931,1036,...,John,Crispin-Bailey,Male,No,No,0.0,5912,0.115681,0.110877,117283
4513,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Conservative,Con,PP52,4,...,Julian,Sturdy,Male,Yes,Yes,4079.0,13770,0.269440,-0.226871,4113
4514,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Labour,Lab,PP53,15,...,Luke,Charters,Male,No,No,5199.0,23161,0.453195,0.153816,3440

**SELECTING SPECIFIC COLUMNS USING PANDAS**

In [ ]:
# selecting a single variable using pandas

# Univariate: A univariate is a kind of findings that is carried out on a single varraible
election_df['Party name']

0         Heritage Party
1            Independent
2       Liberal Democrat
3                  Green
4           Conservative
              ...
4510               Green
4511    Liberal Democrat
4512           Reform UK
4513        Conservative
4514              Labour
Name: Party name, Length: 4515, dtype: object

In [ ]:
election_df['Party name'].unique()

array(['Heritage Party', 'Independent', 'Liberal Democrat', 'Green',
       'Conservative', 'Plaid Cymru', 'Reform UK', 'Labour',
       'Trade Unionist and Socialist Coalition', 'Scottish Family Party',
       'Alba Party', 'Scottish Green Party', 'Scottish National Party',
       'British Unionist Party B.U.P.', 'Hampshire Independents',
       'Workers Party of Britain', 'Sovereignty',
       'Social Democratic Party', 'Ashfield Independents', 'Consensus',
       'Climate Party', 'Socialist Labour Party',
       'Christian Peoples Alliance Party', 'English Democrats',
       'The Yorkshire Party', 'Party of Women',
       'British Democratic Party', 'Independence for Scotland Party',
       'Labour and Co-operative', 'Rejoin EU',
       'Social Democratic and Labour Party', 'Ulster Unionist Party',
       'Traditional Unionist Voice', 'Alliance',
       'Democratic Unionist Party', 'People Before Profit Alliance',
       'Sinn Fein', 'Aontú', 'Animal Welfare Party',
       'Alliance for Democracy and Freedom', 'UK Independence Party',
       'Independent Network', 'Freedom Alliance', 'Common Good Party',
       'Transform Party', 'Monster Raving Loony Party',
       'Communist Party of Britain', 'Blue Revolution',
       'Abolish the Welsh Assembly Party', 'English Constitution Party',
       "Women's Equality Party", 'Liberal', 'Rebooting Democracy',
       'Propel', 'Chesterfield And North Derbyshire Independents (CANDI)',
       'Democracy for Chorley', 'Speaker',
       'The Socialist Party of Great Britain',
       'Scottish Libertarian Party',
       'Putting Crewe First, Independent Residents Group',
       'Taking The Initiative Party', 'True & Fair Party',
       'The North East Party', 'Shared Ground',
       'Cross-Community Labour Alternative', 'Fairer Voting Party',
       'Save Us Now', 'Scottish Socialist Party',
       "Christian Party, Proclaiming Christ's Lordship",
       'Linconshire Independents', 'The Peace Party',
       'Workers Revolutionary Party', 'Socialist Equality Party',
       'Kingston Independent Residents Group',
       'Alliance for Green Socialism', 'One Leicester',
       'Liverpool Community Independents', 'National Health Action Party',
       'Communist Future', 'Communist League Election Campaign',
       'Volt United Kingdom', 'South Devon Alliance', 'Libertarian Party',
       'Independent Oxford Alliance', 'The Yoruba Party in the UK',
       'Portsmouth Independent Party', 'Count Binface Party',
       'The Mitre TW9', 'Social Justice party', 'Swale Independents',
       'UK Voice', 'Confelicity', 'Psychedelic Movement',
       'The Common People', 'Stockport Fights Austerity No To Cuts',
       'Independents for Direct Democracy',
       'New Open Non-Political Organised Leadership',
       'Independent Alliance (Kent)', 'Newham Independents Party'],
      dtype=object)

In [ ]:
election_df['Party name'].nunique()

99

In [ ]:
election_df["Party name"].value_counts()

Party name
Conservative                                   635
Liberal Democrat                               630
Reform UK                                      609
Green                                          585
Labour                                         582
                                              ...
Stockport Fights Austerity No To Cuts            1
Independents for Direct Democracy                1
New Open Non-Political Organised Leadership      1
Independent Alliance (Kent)                      1
Newham Independents Party                        1
Name: count, Length: 99, dtype: int64

In [ ]:
# bivariate analysis: This is a process of selecting two variables for analysis

election_df[['Party name', 'Country name']]

            Party name Country name
0       Heritage Party        Wales
1          Independent        Wales
2     Liberal Democrat        Wales
3                Green        Wales
4         Conservative        Wales
...                ...          ...
4510             Green      England
4511  Liberal Democrat      England
4512         Reform UK      England
4513      Conservative      England
4514            Labour      England

[4515 rows x 2 columns]

In [ ]:
# selecting more than two features from the dataset to perform mutli-variate analysis
election_df[['Party name', 'Country name', 'Constituency type']]

            Party name Country name Constituency type
0       Heritage Party        Wales            County
1          Independent        Wales            County
2     Liberal Democrat        Wales            County
3                Green        Wales            County
4         Conservative        Wales            County
...                ...          ...               ...
4510             Green      England            County
4511  Liberal Democrat      England            County
4512         Reform UK      England            County
4513      Conservative      England            County
4514            Labour      England            County

[4515 rows x 3 columns]

In [ ]:
election_df.loc[:, ['Party name', 'Country name'] ]

            Party name Country name
0       Heritage Party        Wales
1          Independent        Wales
2     Liberal Democrat        Wales
3                Green        Wales
4         Conservative        Wales
...                ...          ...
4510             Green      England
4511  Liberal Democrat      England
4512         Reform UK      England
4513      Conservative      England
4514            Labour      England

[4515 rows x 2 columns]

In [ ]:
election_df.iloc[:, [6, 4]]

            Party name Country name
0       Heritage Party        Wales
1          Independent        Wales
2     Liberal Democrat        Wales
3                Green        Wales
4         Conservative        Wales
...                ...          ...
4510             Green      England
4511  Liberal Democrat      England
4512         Reform UK      England
4513      Conservative      England
4514            Labour      England

[4515 rows x 2 columns]

In [ ]:
# using query method to slect features from our dataset
election_df.query('`Party name` == "Green"')

,ONS ID,ONS region ID,Constituency name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,MNIS party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
3,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Green,Green,PP63,44,...,Nigel,Hill,Male,No,No,0.0,1094,0.030597,0.014817,92890
38,E14001063,E12000008,Aldershot,South East,England,Borough,Green,Green,PP63,44,...,Ed,Neville,Male,No,No,0.0,2155,0.044393,0.008910,104012
43,E14001064,E12000005,Aldridge-Brownhills,West Midlands,England,Borough,Green,Green,PP63,44,...,Clare,Nash,Female,No,No,0.0,1746,0.042677,0.024228,82753
58,E14001065,E12000002,Altrincham and Sale West,North West,England,Borough,Green,Green,PP63,44,...,Geraldine,Coggins,Female,No,No,0.0,3699,0.071892,0.043296,4639
64,W07000082,W92000004,Alyn and Deeside,Wales,Wales,County,Green,Green,PP63,44,...,Karl,Macnaughton,Male,No,No,0.0,1926,0.044386,0.000000,1431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4479,E14001602,E12000002,Wythenshawe and Sale East,North West,England,Borough,Green,Green,PP63,44,...,Melanie,Earp,Female,No,No,0.0,4133,0.105617,0.070786,43728
4484,E14001603,E12000009,Yeovil,South West,England,County,Green,Green,PP63,44,...,Serena,Wootton,Female,No,No,0.0,2403,0.049089,0.021044,92410
4492,W07000112,W92000004,Ynys Môn,Wales,Wales,County,Green,Green,PP63,44,...,Martin,Schwaller,Male,No,No,0.0,604,0.018512,0.000000,116504
4503,E14001604,E12000003,York Central,Yorkshire and The Humber,England,Borough,Green,Green,PP63,44,...,Lars,Kramm,Male,No,No,0.0,5185,0.119682,0.077808,50749
4510,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Green,Green,PP63,44,...,Michael,Kearney,Male,No,No,0.0,2212,0.043283,0.043118,101413

ASSIGNMENT 2:

Using the election dataset, do the following tasks:

1. df['col'].isin([x,y,z]) – Select rows where values are in a list.

2. df['col'].between(a, b) – Select rows where values fall between a and b.

3. df['col'].duplicated() – Filter duplicated rows.

4. df.nunique() with conditions – Identify unique counts for filtering.


submit the assignment to: michaelanietiejack@gmail.com

In [ ]:
election_df

,ONS ID,ONS region ID,Constituency name,Region name,Country name,Constituency type,Party name,Party abbreviation,Electoral Commission party ID,MNIS party ID,...,Candidate first name,Candidate surname,Candidate gender,Sitting MP,Former MP,Member MNIS ID,Votes,Share,Change,DC Person ID
0,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Heritage Party,HPUK,PP12550,1037,...,Rhiannon,Morrissey,Female,No,No,0.0,183,0.005118,0.000000,117009
1,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Independent,Ind,0,8,...,Captain,Beany,Male,No,No,0.0,618,0.017284,0.000000,20
2,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Liberal Democrat,LD,PP90,17,...,Justin,Griffiths,Male,No,No,0.0,916,0.025619,-0.011412,89373
3,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Green,Green,PP63,44,...,Nigel,Hill,Male,No,No,0.0,1094,0.030597,0.014817,92890
4,W07000081,W92000004,Aberafan Maesteg,Wales,Wales,County,Conservative,Con,PP52,4,...,Abigail,Mainon,Female,No,No,0.0,2903,0.081191,-0.145088,72976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4510,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Green,Green,PP63,44,...,Michael,Kearney,Male,No,No,0.0,2212,0.043283,0.043118,101413
4511,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Liberal Democrat,LD,PP90,17,...,Andrew,Hollyer,Male,No,No,0.0,5496,0.107541,-0.079162,34649
4512,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Reform UK,RUK,PP7931,1036,...,John,Crispin-Bailey,Male,No,No,0.0,5912,0.115681,0.110877,117283
4513,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Conservative,Con,PP52,4,...,Julian,Sturdy,Male,Yes,Yes,4079.0,13770,0.269440,-0.226871,4113
4514,E14001605,E12000003,York Outer,Yorkshire and The Humber,England,County,Labour,Lab,PP53,15,...,Luke,Charters,Male,No,No,5199.0,23161,0.453195,0.153816,3440

In [ ]:
election_df['Party name'].isin(['Green','Independent','Liberal Democrat'])

0       False
1        True
2        True
3        True
4       False
        ...
4510     True
4511     True
4512    False
4513    False
4514    False
Name: Party name, Length: 4515, dtype: bool

In [ ]:
election_df['Votes'].between(1,200)

0        True
1       False
2       False
3       False
4       False
        ...
4510    False
4511    False
4512    False
4513    False
4514    False
Name: Votes, Length: 4515, dtype: bool

In [ ]:
election_df['Votes'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4510    False
4511    False
4512     True
4513    False
4514    False
Name: Votes, Length: 4515, dtype: bool

In [ ]:
election_df['Votes'].duplicated().sum()

np.int64(882)

In [ ]:
election_df['Country name'].nunique()
# election_df.loc[:, election_df.nunique() == 2]

4

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()


df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
df.groupby(['Pclass', 'Sex'])['Pclass'].count()

Pclass  Sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: Pclass, dtype: int64

In [ ]:
sur = df[(df['Survived'] == 1) | (df['Sex'] == "female")]
sur

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
old = df.query("Age >= 50 & Survived == 1")
old

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
259,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.0,0,1,230433,26.0000,NaN,S
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C
366,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.2500,D37,C
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S
458,459,1,2,"Toomey, Miss. Ellen",female,50.0,0,0,F.C.C. 13531,10.5000,NaN,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
496,497,1,1,"Eustis, Miss. Elizabeth Mussey",female,54.0,1,0,36947,78.2667,D20,C
513,514,1,1,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",female,54.0,1,0,PC 17603,59.4000,NaN,C
526,527,1,2,"Ridsdale, Miss. Lucy",female,50.0,0,0,W./C. 14258,10.5000,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
571,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
591,592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.0,1,0,36947,78.2667,D20,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.0,2,0,PC 17611,133.6500,NaN,S
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S
774,775,1,2,"Hocking, Mrs. Elizabeth (Eliza Needs)",female,54.0,1,3,29105,23.0000,NaN,S
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.5000,B69,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [ ]:
filt = df.query("SibSp > 0 & Pclass == 3")
filt

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
852,853,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C
860,861,0,3,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S